# Generated by Django 4.2.5 on 2024-09-06 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_appliedjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliedjob',
            name='user',
        ),
        migrations.AddField(
            model_name='appliedjob',
            name='candidate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.candidate'),
        ),
    ]
