# Generated by Django 4.2.5 on 2024-09-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_appliedjob_user_appliedjob_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedjob',
            name='date_applied',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='appliedjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=50),
        ),
    ]
